# Generated by Django 4.1.7 on 2023-03-20 22:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crudLePizza', '0002_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='id',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(related_name='+', to='crudLePizza.topping'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='value',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
